language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: r/Qn4Iiui+XnIf0yJJCBXVKZK7pUipZBsPn81otF+ryuqmGKhWxJze99PfDbye+wffosqjhg8QU3fG3XOuZPvroF4OUB4z5JoVp1pB73N9v9ABgWFkw1Cr5pGP4os/0bbthXUVdgOx3+yZKCc5gmSLIH0Zv1YRIHZBl1qVstdzcp/sRvpsLrWPWglmcHk+kWtxB5t+KbM37wxdWU7PyyJdmTws8oMIld04x1tejWKKLQAQ27MDzdDol7MRiGcpB1p1C8yGPLuZK8iIL77xakFSgSivZV+aMq/sIRJ8NGPd3XSrrEYrnHGXuxJAcncGGLlijN9/1bvlOyqwfyF1VBcgiR0zcj787Bni9lqxxGzkpRbzMpVuJNuncFMBCBfe4QYH4/vOcuxwDo5LEZb/rkQRmrX+71BbiMMUzsnlPMN8TwbgFs/3z7iqwN5eU2Ms2iNJZhGpgDYqhg5k5a9lH6z8XArbMJ5gJt5qByNToaMQX9fWLtDGaIzhtJgq7lzuhNMGawwjIP7dUj8zVwiizxHDlUVW9lHa62qC9rrM0yNy6mogHIx1cl8+A/kxOQs6ZJCA6i6AoN2IkgesMwsN0GCWanD+U4z7tPHmiCAR5AEUlnQWoKJMPANreiOiFg6SzAL6uVWrW++Mktd2fpAnPAk7ywGuXN9unBGnSe9zJmSbY=
  - secure: GV5pc4LpHan3SCkpsWj+gddi8feBoBF919ViPPAKJOBnjTt17E+FI7YbNRGT7nqt3hv5WxDDofkbzNMqaNSEdTcGPzhTjQoBeJkQa1BulzEpOJrmw+HJ7hTiQzZDC+1iDtjcNJ0Fy+OOzHt8IkIHbGNA+8z3EG/ZQR0F66G1nfWD9u4xdZtzFeoZPCNtfRZVEYiQv/OUzM4/6tydKSkbaWVwKWrsV0Kb+h5TY3Z1k8iQ0VPQhAorXuxzOwJZd/FiPI7a2qWooVwsFeIXOUUJoV5vfYrPrrd8iErJ9jMVF5kYv182d2V8PFNoD0Wr2tUTZ62cla/9ivIGSVtj0Z2XrpYC+9t22TTYraIb3KjkTicsPt3EYfGdL6cXCz/d94T8QxtsSS537N1K04msyeN5Ub4nhtAZ11SKxDb4197eGX3bb0aPm5IFG4i1o56FftXxTfbxSPgIOCVcFXVobe3G9zCO8m2YFBbc7F+nupvmlEoh8ni52NL+7e7UsfsCJJu7PwVdtERHBIQQtKMgxgZBgyI/qoe3ljebi1oluju/S3d7Qi9E01ESy9N+OGzK4UgsiNWaZ2gHds4VBSGwoganmrBWo31wqtL3zAbeJKgY7fTT8rb52uoZ+e3od8fCodCnsTu6S/ZuUthQqGodhuhZuBqCdkukLjoHnWgaZ8qNuso=
