baseurl = "https://www.karankhanchandani.com/"
languageCode = "en-us"
title = "Karan Khanchandani"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Karan Khanchandani"
	description = "Coder. Gamer. Dreamer."
	
	# Repository
	#provider = "GitHub"
	#repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	#version = "1.0.0"
	logo = "img/kk.jpg"
	#favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "indigo"
    	accent  = "light-blue"

    [params.font]
    	text = "Roboto"
    	code = "Raleway"


[social]
	twitter = ""
	github  = "Karan-Khanchandani"
	email   = "karan.khanchandani94@gmail.com"


#[[menu.main]]
#	name   = "Material"
#	url    = "/"
#	weight = 0

[[menu.main]]
	name   = "Articles"
	url    = "articles/"
	weight = 10

[[menu.main]]
	name   = "About"
	url    = "about/"
	weight = 20

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
